[package]
name = "mqttsn-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
no-std-net = "0.6.0"
format_no_std = "1.0.0"
nrf-modem = {version = "0.2.1", features = ["defmt"]}
heapless = "0.7.16"
tokio = { version = "1.26.0", features = ["full"] }
mqtt-sn = "0.2.2"
bimap = { version = "0.6.3", default-features = false }
byte = "0.2.6"

[features]
default = ["std"]
std = []
